Feature: Matching Engine

  @Matching_Engine_IOI
  Scenario Outline: Submit IOI Order
    Given User Navigates to Landing Page of Ilex
    And User Login to Ilex with valid credentials
    When Click on Order Capture from Navigation Bar
    Then Able to see Buy/Sell Options in Order Capture Page
    When User Clicks on Buy button
    Then Validate IOI and Req Radio Buttons
    When Select IOI
    Then Enter Order Capture Informations for IOI "<Status>""<IOIName>""<GoodUntil>""<Borrower>""<Industry>""<RiskCountry>""<Purpose>""<MinSpread>""<MaxSpread>""<FacilityType>""<MinTicket>""<MaxTicket>""<Currency>""<MinTenor>""<MaxTenor>""<TransferType>""<Seniority>""<MarketType>""<GreenLoans>""<Security>""<ECA>"
    Then User Submits IOI Order
    #  And Order Submitted with Expected Message "<Expected Message>"
    Then User Logout from Ilex

    Examples: 
      # | Status | IOIName       | GoodUntil     | Borrower | Industry              | RiskCountry | Purpose             | MinSpread | MaxSpread | FacilityType | MinTicket | MaxTicket | Currency | MinTenor | MaxTenor | TransferType                        | Seniority | MarketType | GreenLoans | Security | ECA | Expected Message         |
      #  | Submit | IOITestUIAuto | 2021-March-10 |          | Construction          | Australia   | Real Estate Finance |         0 |      1000 | Term Loan A  |         0 |      1000 | SGD      |        0 |       10 | Disclosed funded risk participation | Senior    | Any        | Any        | Any      | Any | Generic Success Message! |
      | Status | IOIName | GoodUntil     | Borrower | Industry              | RiskCountry | Purpose             | MinSpread | MaxSpread | FacilityType       | MinTicket | MaxTicket  | Currency | MinTenor | MaxTenor | TransferType                        | Seniority    | MarketType | GreenLoans | Security | ECA | Expected Message         |
      | Submit | IOI 1   | 2021-April-11 |          | Aerospace and Defense | Australia   | Working capital     |       100 |       200 | Term Loan A        |         0 | 50,000,000 | AUD      |        3 |        5 | Unfunded risk participation         | Senior       | Any        | Any        | Any      | Any | Generic Success Message! |
      | Submit | IOI 2   | 2021-April-11 |          | Basic Materials       | Australia   | Acquisition Finance |       100 |       200 | Term Loan A        |         0 | 50,000,000 | CNY      |        3 |        5 | Disclosed funded risk participation | Senior       | Any        | Any        | Any      | Any | Generic Success Message! |
      | Submit | IOI 3   | 2021-April-11 |          | Energy                | Singapore   | Real Estate Finance |       100 |       200 | Term Loan A        |         0 | 50,000,000 | EUR      |        3 |        5 | Unfunded risk participation         | Senior       | Any        | Any        | Any      | Any | Generic Success Message! |
      | Submit | IOI 4   | 2021-June-13  |          | Automotive            | Hong Kong   | General Corporate   |       100 |       200 | Term Loan A        |         0 | 50,000,000 | HKD      |        3 |        5 | Unfunded risk participation         | Senior       | Any        | Any        | Any      | Any | Generic Success Message! |
      | Submit | IOI 5   | 2021-July-14  |          | Construction          | Singapore       | Project Finance     |       100 |       200 | Term Loan A        |         0 | 50,000,000 | INR      |        3 |        5 | Unfunded risk participation         | Senior       | Any        | Any        | Any      | Any | Generic Success Message! |
      | Submit | IOI 6   | 2021-April-11 |          | Financial Services    | Singapore       | General Corporate   |       100 |       200 | Term Loan A        |         0 | 50,000,000 | USD      |        3 |        5 | Disclosed funded risk participation | Senior       | Any        | Any        | Any      | Any | Generic Success Message! |
      | Submit | IOI 7   | 2021-April-24 |          | Government            | Australia   | Working capital     |         0 |      1000 | Term Loan B        |         0 | 50,000,000 | AUD      |        0 | 15+      | Unfunded risk participation         | Senior       | Any        | Any        | Any      | Any | Generic Success Message! |
      | Submit | IOI 8   | 2021-April-10 |          | Healthcare            | Singapore   | Acquisition Finance |         0 |      1000 | Term Loan B        |         0 | 50,000,000 | CNY      |        0 | 15+      | Unfunded risk participation         | Senior       | Any        | Any        | Any      | Any | Generic Success Message! |
      | Submit | IOI 9   | 2021-April-11 |          | Manufacturing         | Hong Kong   | Real Estate Finance |         0 |      1000 | Term Loan B        |         0 | 50,000,000 | EUR      |        0 | 15+      | Disclosed funded risk participation | Senior       | Any        | Any        | Any      | Any | Generic Success Message! |


  @Matching_Engine_SEC
  Scenario Outline: Add Loan and Run SEC
    Given User Navigates to Landing Page of Ilex
    And User Login to Ilex with seller credentials
    When Click on Order Capture from Navigation Bar
    When User clicks on the Sell button
    Then Validate SEC and Req Radio Buttons
    And Select SEC
    And Clicks and Create Asset Name
    When User Able to see Loan Details Page in My Loans
    Then Enter Loan Details MEngine "<Borrower Name>""<Parent Name>""<Borrower Country>""<Guarantor Name>""<Industry>""<Country of risk>""<Public Rating>""<Internal Rating>""<Target Issuance Date>""<Purpose>""<Deal Description>"
    And Followed by Adding Tranches to it "<Currency>""<Amount>""<Maturity Date>""<Repayment Type>""<Facility Type>""<Seniority Type>""<Distrubution Method>""<Margin>"
    Then User Clicks on List button
    And Order Saved with Expected Message "<Generic Success Message!>"
    And Capture generated Tranche Name
    #  And Validate the Asset Name "<Expected Value>"
    And Click on the Back Button
    When User clicks on the Sell button
    Then Validate SEC and Req Radio Buttons
    And Select SEC
    And Select Asset Value
    And Enter Trade Informations for SEC "<All-in spread (indication)>""<Size (indication) (USD)>""<Min. Ticket (indication) (USD)>""<Invitation valid until>""<Target closing date>"
    Then User clicks on Submit Order
    #  And Order Submitted with Expected Message "<Generic Success Message!>"
    # And User Validate the Shortlisted Investors "<Expected Result>"
    Then User Logout from Ilex
    Given User Navigates to Landing Page of Ilex
    And User Login to Ilex with valid credentials
    When Click on Dashboard from Navigation Bar
    Then Click on Orders
    And Navigate to Active Orders
    And Verify Order Status "<Order Name>"
    Then User Logout from Ilex

    Examples: 
      #  | Borrower Name            | Parent Name | Borrower Country | Guarantor Name | Industry     | Country of risk | Public Rating | Internal Rating | Target Issuance Date | Purpose             | Deal Description | Currency | Amount | Maturity Date | Repayment Type | Facility Type | Seniority Type | Distrubution Method | Margin | Generic Success Message! | Expected Value          | All-in spread (indication) | Size (indication) (USD) | Min. Ticket (indication) (USD) | Invitation valid until | Target closing date | Generic Success Message! | Expected Result        |
      # | CFPC (Singapore) Pte Ltd | QA          | Indonesia        | Testing        | Construction | Australia       | AAA           | AAA             | 2021-April-20        | Real Estate Finance | Dry Test         | SGD      |    123 | 2022-March-24 | Bullet         | Term Loan A   | Senior         | Syndication         |    129 | Generic Success Message! | SING TLA SGD0m Apr21 1Y |                        100 |                     500 |                              5 | 2020-March-10          | 2021-April-11       | Generic Success Message! | Singapore Airlines Ltd |
      | Borrower Name                                     | Parent Name     | Borrower Country | Guarantor Name | Industry              | Country of risk | Public Rating | Internal Rating | Target Issuance Date | Purpose             | Deal Description | Currency | Amount | Maturity Date | Repayment Type | Facility Type      | Seniority Type | Distrubution Method | Margin | Generic Success Message! | Expected Value | All-in spread (indication) | Size (indication) (USD) | Min. Ticket (indication) (USD) | Invitation valid until | Target closing date | Order Name |
      | China Construction Bank Singapore                 | Test Automation | Australia        | QA             | Aerospace and Defense | Australia       | AAA           | AA              | 2021-March-10        | Working capital     | Dry Auto Run     | AUD      |    100 | 2022-March-10 | Bullet         | Term Loan A        | Senior         | Syndication         |    200 | Generic Success Message! | Expected Value |                        100 |                      50 |                              0 | 2022-April-11          | 2022-May-10         | IOI 1      |
      | Gunvor Singapore Pte Ltd                          | Test Automation | Australia           | QA             | Basic Materials       | Australia       | AAA           | AA              | 2021-March-10        | Acquisition Finance | Dry Auto Run     | CNY      |    200 | 2022-March-10 | Revolving      | Term Loan A        | Senior         | Syndication         |    300 | Generic Success Message! | Expected Value |                        100 |                      50 |                              0 | 2022-April-11          | 2022-May-10         | IOI 2      |
      | Tata International Singapore Pte Ltd              | Test Automation | Australia            | QA             | Energy                | Singapore       | AAA           | AA              | 2021-March-10        | Real Estate Finance | Dry Auto Run     | EUR      |    300 | 2022-March-10 | Bullet         | Term Loan A        | Senior         | Bilateral           |    200 | Generic Success Message! | Expected Value |                        100 |                      50 |                              0 | 2022-April-11          | 2022-May-10         | IOI 3      |
      | Aisin Seiki Co Ltd                                | Test Automation | Hong Kong            | QA             | Automotive            | Hong Kong       | AAA           | AA              | 2021-March-10        | General Corporate   | Dry Auto Run     | HKD      |    300 | 2022-March-10 | Bullet         | Term Loan A        | Senior         | Bilateral           |    200 | Generic Success Message! | Expected Value |                        100 |                      50 |                              0 | 2022-April-11          | 2022-May-10         | IOI 4      |
      | CFPC (Singapore) Pte Ltd                          | Test Automation | Hong Kong           | QA             | Construction          | Japan           | AAA           | AA              | 2021-March-10        | Project Finance     | Dry Auto Run     | INR      |    300 | 2022-March-10 | Bullet         | Term Loan A        | Senior         | Bilateral           |    200 | Generic Success Message! | Expected Value |                        100 |                      50 |                              0 | 2022-April-11          | 2022-May-10         | IOI 5      |
      | China Construction Bank Singapore                 | Test Automation | Hong Kong          | QA             | Financial Services    | China           | AAA           | AA              | 2021-March-10        | General Corporate   | Dry Auto Run     | USD      |    300 | 2022-March-10 | Bullet         | Term Loan A        | Senior         | Bilateral           |    200 | Generic Success Message! | Expected Value |                        100 |                      50 |                              0 | 2022-April-11          | 2022-May-10         | IOI 6      |
      | Gunvor Singapore Pte Ltd                          | Test Automation | Hong Kong        | QA             | Government            | Australia       | AAA           | AA              | 2021-March-10        | Working capital     | Dry Auto Run     | AUD      |    300 | 2022-March-10 | Bullet         | Term Loan B        | Senior         | Bilateral           |    200 | Generic Success Message! | Expected Value |                          0 |                      50 |                              0 | 2022-April-11          | 2022-May-10         | IOI 7      |
      | Tata International Singapore Pte Ltd              | Test Automation | Singapore            | QA             | Healthcare            | Singapore       | AAA           | AA              | 2021-March-10        | Acquisition Finance | Dry Auto Run     | CNY      |    300 | 2022-March-10 | Bullet         | Term Loan B        | Senior         | Bilateral           |    200 | Generic Success Message! | Expected Value |                          0 |                      50 |                              0 | 2022-April-11          | 2022-May-10         | IOI 8      |
      | Singapore Airlines Ltd                            | Test Automation | Singapore        | QA             | Manufacturing         | Hong Kong       | AAA           | AA              | 2021-March-10        | Real Estate Finance | Dry Auto Run     | EUR      |    300 | 2022-March-10 | Bullet         | Term Loan B        | Senior         | Bilateral           |    200 | Generic Success Message! | Expected Value |                          0 |                      50 |                              0 | 2022-April-11          | 2022-May-10         | IOI 9      |
      | HSBC Institutional Trust Services (Singapore) Ltd | Test Automation | Singapore          | QA             | Media                 | Japan           | AAA           | AA              | 2021-March-10        | General Corporate   | Dry Auto Run     | HKD      |    300 | 2022-March-10 | Bullet         | Term Loan B        | Senior         | Bilateral           |    200 | Generic Success Message! | Expected Value |                          0 |                      50 |                              0 | 2022-April-11          | 2022-May-10         | IOI 10     |
      | Shun Tak Real Estate (Singapore) Pte Ltd          | Test Automation | Singapore            | QA             | Real Estate           | China           | AAA           | AA              | 2021-March-10        | Project Finance     | Dry Auto Run     | INR      |    300 | 2022-March-10 | Bullet         | Term Loan B        | Senior         | Bilateral           |    200 | Generic Success Message! | Expected Value |                          0 |                      50 |                              0 | 2022-April-11          | 2022-May-10         | IOI 11     |
      | CFPC (Singapore) Pte Ltd                          | Test Automation | Malaysia         | QA             | Retail                | Australia       | AAA           | AA              | 2021-March-10        | General Corporate   | Dry Auto Run     | USD      |    300 | 2022-March-10 | Bullet         | Term Loan B        | Senior         | Bilateral           |    200 | Generic Success Message! | Expected Value |                          0 |                      50 |                              0 | 2022-April-11          | 2022-May-10         | IOI 12     |
      | Unic Memory Technology (Singapore) Pte Ltd        | Test Automation | Taiwan           | QA             | Mining                | Australia       | AAA           | AA              | 2021-March-10        | Working capital     | Dry Auto Run     | USD      |    300 | 2022-March-10 | Bullet         | Term Loan A        | Senior         | Bilateral           |    200 | Generic Success Message! | Expected Value |                          0 |                      50 |                              0 | 2022-April-11          | 2022-May-10         | IOI 13     |
      | Gunvor Singapore Pte Ltd                          | Test Automation | United Kingdom   | QA             | Services              | Australia       | AAA           | AA              | 2021-March-10        | Acquisition Finance | Dry Auto Run     | AUD      |    300 | 2022-March-10 | Bullet         | Term Loan A        | Senior         | Bilateral           |    200 | Generic Success Message! | Expected Value |                          0 |                      50 |                              0 | 2022-April-11          | 2022-May-10         | IOI 14     |
      | Unic Memory Technology (Singapore) Pte Ltd        | Test Automation | United States    | QA             | Shipping              | Singapore       | AAA           | AA              | 2021-March-10        | Real Estate Finance | Dry Auto Run     | SGD      |    300 | 2022-March-10 | Bullet         | Term Loan A        | Senior         | Bilateral           |    200 | Generic Success Message! | Expected Value |                          0 |                      50 |                              0 | 2022-April-11          | 2022-May-10         | IOI 15     |
      | HSBC Institutional Trust Services (Singapore) Ltd | Test Automation | Australia        | QA             | Technology            | Hong Kong       | AAA           | AA              | 2021-March-10        | General Corporate   | Dry Auto Run     | USD      |    300 | 2022-March-10 | Bullet         | Term Loan B        | Senior         | Bilateral           |    200 | Generic Success Message! | Expected Value |                          0 |                      50 |                              0 | 2022-March-11          | 2022-May-10         | IOI 16     |
      | Singapore Airlines Ltd                            | Test Automation | Canada           | QA             | Telecommunications    | Japan           | AAA           | AA              | 2021-March-10        | Project Finance     | Dry Auto Run     | HKD      |    300 | 2022-March-10 | Bullet         | Revolving Facility | Senior         | Bilateral           |    200 | Generic Success Message! | Expected Value |                          0 |                      50 |                              0 | 2022-April-11          | 2022-May-10         | IOI 17     |
      | Aier Eye International (Singapore) Pte Ltd        | Test Automation | China            | QA             | Transportation        | China           | AAA           | AA              | 2021-March-10        | General Corporate   | Dry Auto Run     | JPY      |    300 | 2022-March-10 | Bullet         | Revolving Facility | Mezzanine      | Bilateral           |    200 | Generic Success Message! | Expected Value |                          0 |                      50 |                              0 | 2022-April-11          | 2022-May-10         | IOI 18     |
      | CFPC (Singapore) Pte Ltd                          | Test Automation | Japan            | QA             | Utilities             | Australia       | AAA           | AA              | 2021-March-10        | Working capital     | Dry Auto Run     | USD      |    300 | 2022-March-10 | Bullet         | Revolving Facility | Mezzanine      | Bilateral           |    200 | Generic Success Message! | Expected Value |                        100 |                      50 |                              0 | 2022-April-11          | 2022-May-10         | IOI 19     |
      | Aisin Seiki Co Ltd                                | Test Automation | France           | QA             | Wholesale             | Australia       | AAA           | AA              | 2021-March-10        | Acquisition Finance | Dry Auto Run     | AUD      |    300 | 2022-March-10 | Bullet         | Term Loan A        | Mezzanine      | Bilateral           |    200 | Generic Success Message! | Expected Value |                        100 |                      50 |                              0 | 2022-April-11          | 2022-May-10         | IOI 20     |
      | CFPC (Singapore) Pte Ltd                          | Test Automation | Germany          | QA             | Basic Materials       | Singapore       | AAA           | AA              | 2021-March-10        | Real Estate Finance | Dry Auto Run     | SGD      |    300 | 2022-March-10 | Bullet         | Term Loan A        | Mezzanine      | Bilateral           |    200 | Generic Success Message! | Expected Value |                        100 |                      50 |                              0 | 2022-April-11          | 2022-May-10         | IOI 21     |
      | China Construction Bank Singapore                 | Test Automation | Hong Kong        | QA             | Energy                | Hong Kong       | AAA           | AA              | 2021-March-10        | General Corporate   | Dry Auto Run     | USD      |    300 | 2022-March-10 | Bullet         | Term Loan B        | Mezzanine      | Bilateral           |    200 | Generic Success Message! | Expected Value |                        100 |                      50 |                              0 | 2022-April-11          | 2022-May-10         | IOI 22     |
      | Gunvor Singapore Pte Ltd                          | Test Automation | India            | QA             | Automotive            | India           | AAA           | AA              | 2021-March-10        | Project Finance     | Dry Auto Run     | HKD      |    300 | 2022-March-10 | Revolving      | Revolving Facility | Senior         | Syndication         |    200 | Generic Success Message! | Expected Value |                        100 |                      50 |                              0 | 2022-April-11          | 2022-May-10         | IOI 23     |
      | Tata International Singapore Pte Ltd              | Test Automation | Indonesia        | QA             | Construction          | India           | AAA           | AA              | 2021-March-10        | General Corporate   | Dry Auto Run     | CNY      |    300 | 2022-March-10 | Revolving      | Revolving Facility | Senior         | Syndication         |    200 | Generic Success Message! | Expected Value |                        100 |                      50 |                              0 | 2022-April-11          | 2022-May-10         | IOI 24     |
      | Singapore Airlines Ltd                            | Test Automation | Ireland          | QA             | Financial Services    | Australia       | AAA           | AA              | 2021-March-10        | Working capital     | Dry Auto Run     | USD      |    300 | 2022-March-10 | Revolving      | Term Loan B        | Senior         | Syndication         |    200 | Generic Success Message! | Expected Value |                          0 |                      50 |                              0 | 2022-April-11          | 2022-May-10         | IOI 25     |
      | HSBC Institutional Trust Services (Singapore) Ltd | Test Automation | Japan            | QA             | Government            | Australia       | AAA           | AA              | 2021-March-10        | Acquisition Finance | Dry Auto Run     | HKD      |    300 | 2022-March-10 | Revolving      | Term Loan B        | Senior         | Syndication         |    200 | Generic Success Message! | Expected Value |                          0 |                      50 |                              0 | 2022-April-11          | 2022-May-10         | IOI 26     |
      | Shun Tak Real Estate (Singapore) Pte Ltd          | Test Automation | Malaysia         | QA             | Healthcare            | Singapore       | AAA           | AA              | 2021-March-10        | Real Estate Finance | Dry Auto Run     | JPY      |    300 | 2022-March-10 | Revolving      | Term Loan B        | Subordinated   | Syndication         |    500 | Generic Success Message! | Expected Value |                          0 |                      50 |                              0 | 2022-April-11          | 2022-May-10         | IOI 27     |
      | CFPC (Singapore) Pte Ltd                          | Test Automation | Taiwan           | QA             | Manufacturing         | Hong Kong       | AAA           | AA              | 2021-March-10        | General Corporate   | Dry Auto Run     | USD      |    300 | 2022-March-10 | Revolving      | Revolving Facility | Subordinated   | Syndication         |    500 | Generic Success Message! | Expected Value |                          0 |                      50 |                              0 | 2022-April-11          | 2022-May-10         | IOI 28     |
      | Unic Memory Technology (Singapore) Pte Ltd        | Test Automation | United Kingdom   | QA             | Media                 | India           | AAA           | AA              | 2021-March-10        | Project Finance     | Dry Auto Run     | AUD      |    300 | 2022-March-10 | Revolving      | Revolving Facility | Subordinated   | Syndication         |    500 | Generic Success Message! | Expected Value |                          0 |                      50 |                              0 | 2022-April-11          | 2022-May-10         | IOI 29     |
      | Gunvor Singapore Pte Ltd                          | Test Automation | United States    | QA             | Real Estate           | India           | AAA           | AA              | 2021-March-10        | General Corporate   | Dry Auto Run     | SGD      |    300 | 2022-March-10 | Revolving      | Revolving Facility | Subordinated   | Syndication         |    500 | Generic Success Message! | Expected Value |                          0 |                      50 |                              0 | 2022-April-11          | 2022-May-10         | IOI 30     |
      | MAIF 2 Investments Singapore Pte Ltd              | Test Automation | Australia        | QA             | Retail                | Australia       | AAA           | AA              | 2021-March-10        | Working capital     | Dry Auto Run     | USD      |    300 | 2022-March-10 | Revolving      | Revolving Facility | Subordinated   | Syndication         |    500 | Generic Success Message! | Expected Value |                        100 |                      50 |                              0 | 2022-April-11          | 2022-May-10         | IOI 31     |
      | HSBC Institutional Trust Services (Singapore) Ltd | Test Automation | Canada           | QA             | Mining                | Australia       | AAA           | AA              | 2021-March-10        | Acquisition Finance | Dry Auto Run     | HKD      |    300 | 2022-March-10 | Revolving      | Term Loan A        | Senior         | Syndication         |    500 | Generic Success Message! | Expected Value |                        100 |                      50 |                              0 | 2022-April-11          | 2022-May-10         | IOI 32     |
      | Singapore Airlines Ltd                            | Test Automation | China            | QA             | Services              | Singapore       | AAA           | AA              | 2021-March-10        | Real Estate Finance | Dry Auto Run     | CNY      |    300 | 2022-March-10 | Revolving      | Term Loan A        | Senior         | Syndication         |    500 | Generic Success Message! | Expected Value |                        100 |                      50 |                              0 | 2022-April-11          | 2022-May-10         | IOI 33     |
      | Aier Eye International (Singapore) Pte Ltd        | Test Automation | Japan            | QA             | Shipping              | Hong Kong       | AAA           | AA              | 2021-March-10        | General Corporate   | Dry Auto Run     | USD      |    300 | 2022-March-10 | Revolving      | Revolving Facility | Senior         | Syndication         |    500 | Generic Success Message! | Expected Value |                        100 |                      50 |                              0 | 2022-April-11          | 2022-May-10         | IOI 34     |
      | CFPC (Singapore) Pte Ltd                          | Test Automation | France           | QA             | Technology            | India           | AAA           | AA              | 2021-March-10        | Project Finance     | Dry Auto Run     | HKD      |    300 | 2022-March-10 | Revolving      | Revolving Facility | Senior         | Syndication         |    500 | Generic Success Message! | Expected Value |                        100 |                      50 |                              0 | 2022-April-11          | 2022-May-10         | IOI 35     |
      | Aisin Seiki Co Ltd                                | Test Automation | Germany          | QA             | Telecommunications    | India           | AAA           | AA              | 2021-March-10        | General Corporate   | Dry Auto Run     | JPY      |    300 | 2022-March-10 | Revolving      | Revolving Facility | Senior         | Syndication         |    500 | Generic Success Message! | Expected Value |                        100 |                      50 |                              0 | 2022-April-11          | 2022-May-10         | IOI 36     |
      | CFPC (Singapore) Pte Ltd                          | Test Automation | Hong Kong        | QA             | Transportation        | Australia       | AAA           | AA              | 2021-March-10        | Working capital     | Dry Auto Run     | USD      |    300 | 2022-March-10 | Revolving      | Revolving Facility | Senior         | Syndication         |    500 | Generic Success Message! | Expected Value |                        100 |                      50 |                              0 | 2022-April-11          | 2022-May-10         | IOI 37     |
      | China Construction Bank Singapore                 | Test Automation | India            | QA             | Utilities             | Australia       | AAA           | AA              | 2021-March-10        | Acquisition Finance | Dry Auto Run     | AUD      |    300 | 2022-March-10 | Revolving      | Revolving Facility | Senior         | Syndication         |    500 | Generic Success Message! | Expected Value |                        100 |                      50 |                              0 | 2022-April-11          | 2022-May-10         | IOI 38     |
      | Gunvor Singapore Pte Ltd                          | Test Automation | Indonesia        | QA             | Wholesale             | Singapore       | AAA           | AA              | 2021-March-10        | Real Estate Finance | Dry Auto Run     | SGD      |    300 | 2022-March-10 | Revolving      | Revolving Facility | Subordinated   | Syndication         |    500 | Generic Success Message! | Expected Value |                        100 |                      50 |                              0 | 2022-April-11          | 2022-May-10         | IOI 39     |
      | Tata International Singapore Pte Ltd              | Test Automation | Ireland          | QA             | Basic Materials       | Hong Kong       | AAA           | AA              | 2021-March-10        | General Corporate   | Dry Auto Run     | USD      |    300 | 2022-March-10 | Revolving      | Revolving Facility | Subordinated   | Syndication         |    500 | Generic Success Message! | Expected Value |                        100 |                      50 |                              0 | 2022-April-11          | 2022-May-10         | IOI 40     |
      | Singapore Airlines Ltd                            | Test Automation | Japan            | QA             | Energy                | India           | AAA           | AA              | 2021-March-10        | Project Finance     | Dry Auto Run     | HKD      |    300 | 2022-March-10 | Revolving      | Term Loan B        | Subordinated   | Syndication         |    500 | Generic Success Message! | Expected Value |                        100 |                      50 |                              0 | 2022-April-11          | 2022-May-10         | IOI 41     |
      | HSBC Institutional Trust Services (Singapore) Ltd | Test Automation | Malaysia         | QA             | Automotive            | Singapore       | AAA           | AA              | 2021-March-10        | General Corporate   | Dry Auto Run     | CNY      |    300 | 2022-March-10 | Revolving      | Term Loan B        | Subordinated   | Syndication         |    500 | Generic Success Message! | Expected Value |                        100 |                      50 |                              0 | 2022-April-11          | 2022-May-10         | IOI 42     |
      | Shun Tak Real Estate (Singapore) Pte Ltd          | Test Automation | Taiwan           | QA             | Construction          | Australia       | AAA           | AA              | 2021-March-10        | Working capital     | Dry Auto Run     | USD      |    300 | 2022-March-10 | Revolving      | Term Loan B        | Subordinated   | Syndication         |    500 | Generic Success Message! | Expected Value |                          0 |                      50 |                              0 | 2022-April-11          | 2022-May-10         | IOI 43     |
      | CFPC (Singapore) Pte Ltd                          | Test Automation | United Kingdom   | QA             | Financial Services    | Australia       | AAA           | AA              | 2021-March-10        | Acquisition Finance | Dry Auto Run     | HKD      |    300 | 2022-March-10 | Revolving      | Term Loan B        | Subordinated   | Syndication         |    500 | Generic Success Message! | Expected Value |                          0 |                      50 |                              0 | 2022-April-11          | 2022-May-10         | IOI 44     |
      | Unic Memory Technology (Singapore) Pte Ltd        | Test Automation | United States    | QA             | Government            | Singapore       | AAA           | AA              | 2021-March-10        | Real Estate Finance | Dry Auto Run     | JPY      |    300 | 2022-March-10 | Revolving      | Term Loan B        | Subordinated   | Syndication         |    500 | Generic Success Message! | Expected Value |                          0 |                      50 |                              0 | 2022-April-11          | 2022-May-10         | IOI 45     |
      | Gunvor Singapore Pte Ltd                          | Test Automation | Australia        | QA             | Healthcare            | Hong Kong       | AAA           | AA              | 2021-March-10        | General Corporate   | Dry Auto Run     | USD      |    300 | 2022-March-10 | Revolving      | Revolving Facility | Subordinated   | Syndication         |    500 | Generic Success Message! | Expected Value |                          0 |                      50 |                              0 | 2022-April-11          | 2022-May-10         | IOI 46     |
      | MAIF 2 Investments Singapore Pte Ltd              | Test Automation | Canada           | QA             | Manufacturing         | India           | AAA           | AA              | 2021-March-10        | Project Finance     | Dry Auto Run     | AUD      |    300 | 2022-March-10 | Revolving      | Revolving Facility | Mezzanine      | Syndication         |    500 | Generic Success Message! | Expected Value |                          0 |                      50 |                              0 | 2022-April-11          | 2022-May-10         | IOI 47     |
      | HSBC Institutional Trust Services (Singapore) Ltd | Test Automation | China            | QA             | Media                 | India           | AAA           | AA              | 2021-March-10        | General Corporate   | Dry Auto Run     | SGD      |    300 | 2022-March-10 | Revolving      | Revolving Facility | Mezzanine      | Syndication         |    500 | Generic Success Message! | Expected Value |                          0 |                      50 |                              0 | 2022-April-11          | 2022-May-10         | IOI 48     |
      | Singapore Airlines Ltd                            | Test Automation | Japan            | QA             | Real Estate           | Australia       | AAA           | AA              | 2021-March-10        | Working capital     | Dry Auto Run     | USD      |    300 | 2022-March-10 | Revolving      | Revolving Facility | Mezzanine      | Syndication         |    500 | Generic Success Message! | Expected Value |                        100 |                      50 |                              0 | 2022-April-11          | 2022-May-10         | IOI 49     |
      | Aier Eye International (Singapore) Pte Ltd        | Test Automation | France           | QA             | Retail                | Australia       | AAA           | AA              | 2021-March-10        | Acquisition Finance | Dry Auto Run     | HKD      |    300 | 2022-March-10 | Revolving      | Revolving Facility | Mezzanine      | Syndication         |    500 | Generic Success Message! | Expected Value |                        100 |                      50 |                              0 | 2022-April-11          | 2022-May-10         | IOI 50     |
      | Singapore Airlines Ltd                            | Test Automation | Germany          | QA             | Mining                | Singapore       | AAA           | AA              | 2021-March-10        | Real Estate Finance | Dry Auto Run     | CNY      |    300 | 2022-March-10 | Revolving      | Revolving Facility | Mezzanine      | Syndication         |    500 | Generic Success Message! | Expected Value |                        100 |                      50 |                              0 | 2022-April-11          | 2022-May-10         | IOI 51     |
      | Aisin Seiki Co Ltd                                | Test Automation | Hong Kong        | QA             | Services              | Hong Kong       | AAA           | AA              | 2021-March-10        | General Corporate   | Dry Auto Run     | USD      |    300 | 2022-March-10 | Revolving      | Revolving Facility | Mezzanine      | Syndication         |    500 | Generic Success Message! | Expected Value |                        100 |                      50 |                              0 | 2022-April-11          | 2022-May-10         | IOI 52     |
      | CFPC (Singapore) Pte Ltd                          | Test Automation | India            | QA             | Shipping              | India           | AAA           | AA              | 2021-March-10        | Project Finance     | Dry Auto Run     | HKD      |    300 | 2022-March-10 | Revolving      | Revolving Facility | Mezzanine      | Syndication         |    500 | Generic Success Message! | Expected Value |                        100 |                      50 |                              0 | 2022-April-11          | 2022-May-10         | IOI 53     |
      | China Construction Bank Singapore                 | Test Automation | Indonesia        | QA             | Technology            | India           | AAA           | AA              | 2021-March-10        | General Corporate   | Dry Auto Run     | JPY      |    300 | 2022-March-10 | Revolving      | Term Loan A        | Mezzanine      | Syndication         |    500 | Generic Success Message! | Expected Value |                        100 |                      50 |                              0 | 2022-April-11          | 2022-May-10         | IOI 54     |
      | Gunvor Singapore Pte Ltd                          | Test Automation | Ireland          | QA             | Telecommunications    | Australia       | AAA           | AA              | 2021-March-10        | Working capital     | Dry Auto Run     | USD      |    300 | 2022-March-10 | Revolving      | Term Loan A        | Mezzanine      | Syndication         |    500 | Generic Success Message! | Expected Value |                        100 |                      50 |                              0 | 2022-April-11          | 2022-May-10         | IOI 55     |
      | Tata International Singapore Pte Ltd              | Test Automation | Japan            | QA             | Transportation        | Australia       | AAA           | AA              | 2021-March-10        | Acquisition Finance | Dry Auto Run     | AUD      |    300 | 2022-March-10 | Revolving      | Term Loan A        | Senior         | Syndication         |    500 | Generic Success Message! | Expected Value |                        100 |                      50 |                              0 | 2022-April-11          | 2022-May-10         | IOI 56     |
      | Singapore Airlines Ltd                            | Test Automation | Malaysia         | QA             | Utilities             | Singapore       | AAA           | AA              | 2021-March-10        | Real Estate Finance | Dry Auto Run     | SGD      |    300 | 2022-March-10 | Revolving      | Term Loan A        | Senior         | Syndication         |    500 | Generic Success Message! | Expected Value |                        100 |                      50 |                              0 | 2022-April-11          | 2022-May-10         | IOI 57     |
      | HSBC Institutional Trust Services (Singapore) Ltd | Test Automation | Taiwan           | QA             | Wholesale             | Hong Kong       | AAA           | AA              | 2021-March-10        | General Corporate   | Dry Auto Run     | USD      |    300 | 2022-March-10 | Revolving      | Term Loan A        | Senior         | Syndication         |    500 | Generic Success Message! | Expected Value |                        100 |                      50 |                              0 | 2022-April-11          | 2022-May-10         | IOI 58     |
      | Shun Tak Real Estate (Singapore) Pte Ltd          | Test Automation | United Kingdom   | QA             | Basic Materials       | India           | AAA           | AA              | 2021-March-10        | Project Finance     | Dry Auto Run     | HKD      |    300 | 2022-March-10 | Revolving      | Term Loan A        | Senior         | Syndication         |    500 | Generic Success Message! | Expected Value |                        100 |                      50 |                              0 | 2022-April-11          | 2022-May-10         | IOI 59     |
      | China Construction Bank Singapore                 | Test Automation | United States    | QA             | Energy                | India           | AAA           | AA              | 2021-March-10        | General Corporate   | Dry Auto Run     | CNY      |    300 | 2022-March-10 | Revolving      | Term Loan A        | Senior         | Syndication         |    500 | Generic Success Message! | Expected Value |                        100 |                      50 |                              0 | 2022-April-11          | 2022-May-10         | IOI 60     |
