name: ilex-ui-tests

on:
  push:
    branches:
      - master

jobs:
  Tests:
    runs-on: ubuntu-latest

    name: Run UI Tests
    steps:
      - uses: actions/checkout@v1

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Download and cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Clear DB Tables
        run: |
          aws lambda invoke --function-name db-clear --invocation-type RequestResponse --log-type Tail response

      - name: Run tests
        run: mvn verify -Dcucumber.options="-t @End2End"

      - name: Collect & Upload Test Reports
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: test_reports
          path: ./target/cucumber-ExtendedReports
      # - name: Email Test Reports
      #   if: always()
      #   run: |
      #     bash ./sendmail.sh -s "UI Test Report" -f ssannidhi@palo-it.com -r ssannidhi@palo-it.com -b "UI Test Report" -a ./target/cucumber-ExtendedReports/report.html
